version: '3.8'
services:
  suerp:
    build:
      context: ./suerp
      dockerfile: Dockerfile
    volumes:
      - ./suerp:/app
    ports:
      - "9000:8000"
  n8n:
    image: n8nio/n8n
    ports:
      - "6678:5678"
  db:
    image: postgres:13
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: erp
      POSTGRES_USER: sutech
      POSTGRES_PASSWORD: sutecherp
    ports:
      - "6432:5432"
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "7379:6379"
volumes:
  postgres_data: